/*! \file
    \brief Autogenerated enumerations (Umba Enum Gen)
 */

#pragma once






//#!OutputFormat
enum  OutputFormat
{
    text       = 0 /*!<  */,
    markdown   = 1 /*!<  */,
    html       = 2 /*!<  */

}; // enum 
//#!

MARTY_CPP_MAKE_ENUM_IS_FLAGS_FOR_NON_FLAGS_ENUM(OutputFormat)


